Atomic
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #20
Opened 2024-06-17 13:52 UTC by adrale

2024-06-17 13:57 UTC, ozen2 approved these changes

2024-06-17 14:02 UTC, axeljdev approved these changes

2024-06-17 14:24 UTC, JulienChevreauPro approved these changes

2024-06-17 15:10 UTC, Yoann-Fortin requested changes

2024-06-17 15:10 UTC, Yoann-Fortin commented on client/src/components/atomic/checkBox/BigCheckBox.jsx
It lacks the associated label tag, and too many similar ode to justify a new component.

2024-06-17 15:10 UTC, Yoann-Fortin commented on client/src/components/atomic/checkBox/SmallCheckBox.jsx
It lacks the associated label tag, and too many similar ode to justify a new component.

2024-06-17 15:10 UTC, Yoann-Fortin commented on client/src/components/atomic/tag/Tag.jsx
Too many similar code to justify a new component.

2024-06-17 15:10 UTC, Yoann-Fortin commented on client/src/components/atomic/tag/TagStatus.jsx
It lacks the associated label tag, and too many similar ode to justify a new component.

2024-06-18 07:30 UTC, axeljdev commented on client/package.json
> +    "tailwindcss-animated": "^1.1.0"
if i put it in dev dependencies, it doesn't work

2024-06-18 09:30 UTC, KevinDavoust requested changes

2024-06-18 09:30 UTC, KevinDavoust commented on client/src/components/atomic/card/CardConsultant.jsx
> +          alt="Email"
enlever les alts

2024-06-18 10:05 UTC, KevinDavoust approved these changes

2024-06-18 10:06 UTC, merged