add Values.jsx for HomePage
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #25
Opened 2024-06-18 13:24 UTC by adrale

2024-06-18 13:59 UTC, JulienChevreauPro requested changes
span tag for style

2024-06-18 14:37 UTC, ozen2 commented on client/src/components/Values.jsx
> +    <section className=" p-4 m-4 mt-24 gap-8 bg-[var(--secondary-background-color)] border border-[var(--primary-color)] rounded-md shadow-lg custom-shadow grid grid-cols-2">
article better ?

2024-06-19 07:18 UTC, axeljdev approved these changes

2024-06-19 14:08 UTC, Elea641 approved these changes

2024-06-19 14:09 UTC, merged