S04 us2 company home
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #28
Opened 2024-06-19 14:45 UTC by axeljdev

2024-06-19 14:55 UTC, adrale approved these changes

2024-06-19 16:40 UTC, ozen2 approved these changes

2024-06-19 18:02 UTC, JulienChevreauPro approved these changes

2024-06-20 13:06 UTC, Yoann-Fortin requested changes

2024-06-20 13:06 UTC, Yoann-Fortin commented on client/src/components/atomic/slider/Slider.jsx
In this case, value in alt attribute is necessary

2024-06-20 13:23 UTC, Elea641 approved these changes

2024-06-20 13:23 UTC, merged