S03 us01 navbar
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #3
Opened 2024-06-12 10:15 UTC by ozen2

2024-06-12 12:17 UTC, axeljdev approved these changes

2024-06-12 12:43 UTC, JulienChevreauPro approved these changes

2024-06-12 13:53 UTC, adrale approved these changes

2024-06-13 09:35 UTC, adrale approved these changes

2024-06-13 09:55 UTC, JulienChevreauPro approved these changes

2024-06-13 12:26 UTC, adrale approved these changes

2024-06-13 12:39 UTC, Yoann-Fortin requested changes

2024-06-13 12:39 UTC, Yoann-Fortin commented on client/src/components/Navbar.jsx
> +  const handleChange = () => {
Extract this logic in parent's component will be better

2024-06-13 12:39 UTC, Yoann-Fortin commented on client/src/components/Navbar.jsx
> +          ${
Same here

2024-06-13 12:39 UTC, Yoann-Fortin commented on client/src/services/NavAccess.jsx
Isn't a component, a class will be a good option here

2024-06-14 16:03 UTC, Yoann-Fortin commented on client/src/services/NavAccess.jsx
Isn't a JSX file

2024-06-14 16:03 UTC, Yoann-Fortin commented on client/src/services/NavAccess.jsx
> +    if (!menuRefCurrent) return;
A condition with a true value would be better

2024-06-14 16:03 UTC, Yoann-Fortin commented on client/src/services/NavAccess.jsx
> +    if (!menuRefCurrent) return;
Same

2024-06-14 16:03 UTC, Yoann-Fortin commented on client/src/services/NavAccess.jsx
> +    if (!menuRefCurrent) return;
A condition with a true value would be better

2024-06-14 16:04 UTC, merged