Registration
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #42
Opened 2024-06-24 11:55 UTC by ozen2

2024-06-24 13:33 UTC, axeljdev approved these changes

2024-06-24 13:36 UTC, JulienChevreauPro approved these changes

2024-06-24 13:53 UTC, KevinDavoust requested changes

2024-06-24 13:53 UTC, KevinDavoust commented on client/src/components/Presentation.jsx
> +      <Button type="button" apply="medium" name="S'inscrire" handleChange={handleChange} />
name serait plutôt subscribe ou register

2024-06-24 13:53 UTC, KevinDavoust commented on client/src/components/ModalRegistration.jsx
> +function ModalRegistration({ handleChange, modalOpen, modalVisible }) {
meilleur nommage pour des booleens, comme dans le dernier fichier

2024-06-25 07:05 UTC, KevinDavoust approved these changes

2024-06-25 07:11 UTC, KevinDavoust requested changes

2024-06-25 07:11 UTC, KevinDavoust commented on client/src/components/Navbar.jsx
>  function Navbar({ handleChange, navOpen, navVisible }) {
renommage des variables ici aussi

2024-06-25 07:29 UTC, KevinDavoust approved these changes

2024-06-25 07:29 UTC, merged