S05 us5 offer page
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #46
Opened 2024-06-25 12:15 UTC by adrale

2024-06-25 13:47 UTC, axeljdev commented on client/src/services/fetchApi.js
> +    console.info(data)
remove console.info

2024-06-25 14:11 UTC, JulienChevreauPro approved these changes

2024-06-25 14:56 UTC, KevinDavoust commented on client/src/components/atomic/card/CardCandidate.jsx
> +export default function CardCandidate({ offer }) {
renommer composant en plus explicite par ex CardOfferForCandidate ou uatre similaire

2024-06-25 15:19 UTC, KevinDavoust requested changes

2024-06-26 14:16 UTC, Elea641 requested changes

2024-06-26 14:16 UTC, Elea641 commented on client/src/App.jsx
> +// import ModalRegistration from "./components/ModalRegistration";
no comment please

2024-06-26 14:16 UTC, Elea641 commented on client/src/App.jsx
> +          {/* <ModalRegistration /> */}
idem

2024-06-26 14:16 UTC, Elea641 commented on client/src/main.jsx
> +const offersUrl = "/api/offers";
url ?

2024-06-26 14:38 UTC, Elea641 approved these changes

2024-06-26 14:38 UTC, merged