Add/Modal for connexion and registration, Offer page and Offer details page. Fix/Little details on css and naming functions and more
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #54
Opened 2024-06-28 09:20 UTC by ozen2

2024-06-28 09:41 UTC, axeljdev approved these changes

2024-07-01 10:02 UTC, Yoann-Fortin requested changes

2024-07-01 10:02 UTC, Yoann-Fortin commented on client/src/services/fetchApi.js
A possible improvement would be to reject an error rather than displaying it in the console. Think about it for certification

2024-07-01 10:02 UTC, Yoann-Fortin commented on server/database/fixtures/TechnoOfferSeeder.js
> +    const numberOfOffers = 10;
Snake case in uppercase to respect convention

2024-07-01 10:02 UTC, Yoann-Fortin commented on server/database/models/OfferRepository.js
Indentation and capitalization for sql keywords please

2024-07-08 16:32 UTC, adrale approved these changes

2024-07-10 14:03 UTC, JulienChevreauPro approved these changes

2024-07-10 15:25 UTC, Yoann-Fortin approved these changes

2024-07-10 15:26 UTC, merged