S05 us02 inscription/Login
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #66
Opened 2024-07-02 13:59 UTC by adrale

2024-07-02 14:40 UTC, ozen2 approved these changes

2024-07-02 15:06 UTC, JulienChevreauPro approved these changes

2024-07-02 15:29 UTC, KevinDavoust requested changes

2024-07-02 15:29 UTC, KevinDavoust commented on client/src/components/ModalRegistration.jsx
>        </footer>
il faudrait mettre le contenu de cette balise footer à l'intérieur de la balise form du composant form modal, par souci de structure HTML

2024-07-02 15:29 UTC, KevinDavoust commented on client/src/components/ModalRegistration.jsx
> +  }).isRequired,
ces 4 champs sont requis

2024-07-02 15:29 UTC, KevinDavoust commented on client/src/components/Navbar.jsx
> +      console.error("Erreur lors de la soumission du formulaire :", err);
pas de log dans la console, plutôt utiliser le return du dessous

2024-07-02 15:29 UTC, KevinDavoust commented on client/src/components/Navbar.jsx
> +      console.error(err);
pareil qu'au dessus

2024-07-02 15:29 UTC, KevinDavoust commented on client/src/services/fetchApi.js
> +    console.error("Erreur lors de la récupération des données :", err);
pas de log dans la console

2024-07-02 15:29 UTC, KevinDavoust commented on client/src/services/fetchApi.js
> +    console.error("Erreur lors de l'envoi des données :", err);
pas de log dans la console

2024-07-03 12:38 UTC, Elea641 requested changes

2024-07-03 12:38 UTC, Elea641 commented on client/src/components/atomic/buttons/ButtonSubmit.jsx
> +function ButtonSubmit({
Pourquoi ne pas créer un bouton générique pour le submit ? pour ne pas avoir de condition d 'affichage ?

2024-07-03 12:38 UTC, Elea641 commented on client/src/components/atomic/card/CardConsultant.jsx
> +        <Button name="Email" img="/src/assets/images/mail.svg" apply="small" />
Comment le bouton peut fonctionner sans fonction ?

2024-07-03 12:38 UTC, Elea641 commented on client/src/components/atomic/modalElements/FormModal.jsx
>    const { isClicked } = useModal();
on ne mélange pas de la logique et de la sémantique svp

2024-07-08 08:50 UTC, KevinDavoust requested changes

2024-07-08 08:50 UTC, KevinDavoust commented on client/src/components/atomic/card/CardConsultant.jsx
> +    alert(`${info}`);
pas d'alert, comme les console.log

2024-07-08 08:50 UTC, KevinDavoust commented on client/src/components/atomic/card/CardConsultant.jsx
> +          handleChange={() => handleClick("Téléphone")}
le handleChange appelle un handleClick ?

2024-07-08 09:58 UTC, Yoann-Fortin requested changes

2024-07-08 09:58 UTC, Yoann-Fortin commented on client/src/components/Navbar.jsx
Much of the logic would have to be exported to a service, and using the Button component would probably be appropriate.

2024-07-08 09:58 UTC, Yoann-Fortin commented on client/src/components/atomic/buttons/Button.jsx
The button type should be the default type, but it must be possible to override it for use in forms where it becomes the submit type.

2024-07-08 09:58 UTC, Yoann-Fortin commented on client/src/components/atomic/card/CardConsultant.jsx
> +    setMessage(`${info}`);
Why not insert the variable value directly?

2024-07-08 09:58 UTC, Yoann-Fortin commented on client/src/components/atomic/card/CardConsultant.jsx
too much code duplication here

2024-07-08 09:58 UTC, Yoann-Fortin commented on server/app/services/auth.js
This middleware also acts as a controller, and should only check the validity of the information transmitted, leaving the rest of the information retrieval and transmission to the dedicated controller.

2024-07-08 09:58 UTC, Yoann-Fortin commented on server/database/models/UserRepository.js
> +  async readByEmailWithPassword(email) {
This method does much more than it should, as does the middleware that calls it

2024-07-08 09:58 UTC, Yoann-Fortin commented on server/app/controllers/authActions.js
Verification should take place in the middleware, and the controller should retrieve the information only.

2024-07-09 08:32 UTC, Yoann-Fortin approved these changes

2024-07-09 08:32 UTC, merged