Add/jwt
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #67
Opened 2024-07-09 14:49 UTC by ozen2

2024-07-10 12:24 UTC, axeljdev approved these changes

2024-07-10 12:24 UTC, axeljdev commented on client/src/pages/CandidateManagement.jsx
> +      <form className="self-center flex flex-col gap-4">
label?

2024-07-10 13:00 UTC, JulienChevreauPro commented on client/src/pages/CandidateManagement.jsx
> +        <SearchInputConsultant placeholder="Rechercher des candidats..." />
and the id?

2024-07-10 13:02 UTC, JulienChevreauPro commented on client/src/pages/CandidateManagement.jsx
> +        <CardConsultant name={userData.firstname} tag={userData.name} />
Don't forget lastName, pleaz

2024-07-10 13:29 UTC, JulienChevreauPro approved these changes

2024-07-10 13:29 UTC, JulienChevreauPro commented on server/app/middlewares/genToken.js
> +  if (!req.user) {
Useless

2024-07-10 13:47 UTC, adrale approved these changes

2024-07-11 09:33 UTC, KevinDavoust requested changes

2024-07-11 09:33 UTC, KevinDavoust commented on client/src/contexts/AuthContext.jsx
> +        console.error("Invalid token", error);
rien dans la console

2024-07-11 09:33 UTC, KevinDavoust commented on server/app/middlewares/genToken.js
> +    next(err);
si ton middleware envoie une réponse le next ne sert à rien

2024-07-11 09:33 UTC, KevinDavoust commented on server/app/middlewares/verifyRole.js
> +  return next();
pas de return, juste next() comme dans les autres middlewares

2024-07-11 09:33 UTC, KevinDavoust commented on server/app/middlewares/verifyToken.js
> +    console.error(err);
rien dans la console

2024-07-11 10:09 UTC, KevinDavoust requested changes

2024-07-11 10:09 UTC, KevinDavoust commented on server/app/middlewares/verifyRole.js
> +  return null;
enlève le return. si le rôle n'est pas le bon tu renvoies une erreur ( ça c'est bon ), sinon tu passes à la suite, donc juste next()

2024-07-11 10:35 UTC, Yoann-Fortin requested changes

2024-07-11 10:35 UTC, Yoann-Fortin commented on server/app/middlewares/verifyRole.js
> +  return null;
Useless

2024-07-11 13:58 UTC, merged