S06 ajout offres
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #76
Opened 2024-07-15 13:32 UTC by JulienChevreauPro

2024-07-15 13:47 UTC, ozen2 approved these changes

2024-07-15 13:50 UTC, axeljdev approved these changes

2024-07-16 07:51 UTC, Yoann-Fortin requested changes

2024-07-16 07:51 UTC, Yoann-Fortin commented on server/app/controllers/companyActions.js
> +  // read,
Comments are no longer useful, given your level of experience.

2024-07-16 07:51 UTC, Yoann-Fortin commented on server/app/controllers/jobActions.js
> +  // read,
See comment above

2024-07-16 07:51 UTC, Yoann-Fortin commented on server/app/controllers/offerActions.js
> +    // Fetch a specific offer from the database based on the provided ID
See comment above

2024-07-16 07:51 UTC, Yoann-Fortin commented on server/app/controllers/technoActions.js
> +// Ready to export the controller functions
See comment above

2024-07-16 07:51 UTC, Yoann-Fortin commented on server/database/models/CompanyRepository.js
Why so much comment code?

2024-07-16 07:51 UTC, Yoann-Fortin commented on server/database/models/JobRepository.js
See comment above

2024-07-16 07:51 UTC, Yoann-Fortin commented on server/database/models/TechnoRepository.js
See comment above

2024-07-16 07:51 UTC, Yoann-Fortin commented on server/app/services/offerTransaction.js
To delete please

2024-07-16 08:23 UTC, JulienChevreauPro commented
Removed useless code

2024-07-16 09:23 UTC, Yoann-Fortin approved these changes

2024-07-16 09:23 UTC, merged