Merge dev to main
WildCodeSchool-2024-02/JS-bdx-0224-P3-Externatic pull request #78
Opened 2024-07-19 12:08 UTC by adrale

2024-07-22 09:08 UTC, JulienChevreauPro approved these changes

2024-07-22 10:14 UTC, axeljdev approved these changes

2024-07-22 13:53 UTC, Yoann-Fortin requested changes

2024-07-22 13:53 UTC, Yoann-Fortin commented on server/app/config.js
> +// app.use(express.static(reactBuildPath));
Your vc or photos will be not rendered if this line is commented

2024-07-23 10:04 UTC, Yoann-Fortin approved these changes

2024-07-23 10:04 UTC, merged